#pragma once

#define FILE_DEVICE_DMON               0x00008554

#define IOCTL_DMON_ZEROSTATS           CTL_CODE( FILE_DEVICE_DMON, 0x01, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_DMON_GETSTATS	           CTL_CODE( FILE_DEVICE_DMON, 0x02, METHOD_NEITHER,  FILE_READ_DATA)

#define IOCTL_DMON_STOPFILTER          CTL_CODE( FILE_DEVICE_DMON, 0x04, METHOD_BUFFERED, FILE_WRITE_DATA )
#define IOCTL_DMON_STARTFILTER         CTL_CODE( FILE_DEVICE_DMON, 0x05, METHOD_BUFFERED, FILE_WRITE_DATA )

#define IOCTL_DMON_PASSTHROUGH         CTL_CODE( FILE_DEVICE_DMON, 0x06, METHOD_BUFFERED, FILE_WRITE_DATA )
#define IOCTL_DMON_NOPASSTHROUGH       CTL_CODE( FILE_DEVICE_DMON, 0x07, METHOD_BUFFERED, FILE_WRITE_DATA )
#define IOCTL_DMON_HOOK                CTL_CODE( FILE_DEVICE_DMON, 0x05, METHOD_BUFFERED, FILE_WRITE_DATA )
#define IOCTL_DMON_UNHOOK              CTL_CODE( FILE_DEVICE_DMON, 0x04, METHOD_BUFFERED, FILE_WRITE_DATA )
